version: '3.8'

networks:
  app:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  educational-app:
    container_name: app
    networks:
      - app
    build:
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/education_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16.1-alpine
    container_name: app-postgres
    networks:
      - app
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=education_db
    ports:
      - "5432:5432"
    restart: unless-stopped
