POST http://localhost:8080/v1/auth/sign-up
Content-Type: application/json

{
  "email": "",
  "fullName": "Empty User",
  "password": "Password"
}

> {%
client.test("Empty fields prevented registration", function() {
  client.assert(response.status === 400, "Response status is not 400");
  client.assert(response.body.email === "Email must not be empty", "Response message does not match expected text");
});
%}
