POST http://localhost:8080/v1/auth/sign-up
Content-Type: application/json

{
  "email": "test@example.com",
  "fullName": "Test User",
  "password": "testPassword"
}

> {%
client.test("User registered successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
  client.assert(response.body.email === "test@example.com", "Response message does not match expected text");
  client.assert(response.body.fullName === "Test User", "Response message does not match expected text");
});
%}
