GET http://localhost:8080/demo

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body === "App is running", "Response body does not match expected text");
});
%}