-- liquibase formatted sql
-- add email_verification_token table

-- changeset dmchmb:1
CREATE TABLE IF NOT EXISTS user_roles
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY REFERENCES users (id) ON DELETE CASCADE ON UPDATE NO ACTION,
    role     VARCHAR(255) NOT NULL
);

-- rollback DROP TABLE user_roles;