-- liquibase formatted sql
-- add refresh_token table

-- changeset dmchmb:1
CREATE TABLE IF NOT EXISTS refresh_tokens
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refresh_token VARCHAR(255) UNIQUE,
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY REFERENCES users(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    expiration_time TIMESTAMP
);

-- rollback DROP TABLE refresh_token;